AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31

Description: Simple Serverless API using SAM

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api

    Properties:
      StageName: prod

      DefinitionBody:
        swagger: "2.0"

        info:
          title: Simple API

          version: "1.0"

        paths:
          /hello:
            get:
              responses:
                "200":
                  description: Success response

  HelloFunction:
    Type: AWS::Serverless::Function

    Properties:

      Runtime: nodejs18.x

      Handler: index.handler

      CodeUri: .

      MemorySize: 128

      Timeout: 10

      Policies:
        - AWSLambdaBasicExecutionRole

      Events:
        ApiEvent:
          Type: Api

          Properties:
            Path: /hello

            Method: get

            RestApiId:
              Ref: ApiGatewayApi

Outputs:
  ApiUrl:
    Description: API Endpoint

    Value:
      Fn::Sub: https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/prod/hello
